import { StyleSheet } from 'react-native';
import { colors } from '../../../theme/colors';
import { scale, verticalScale } from '../../../theme/scale';

export const gpsLocationCardStyles = StyleSheet.create({
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: scale(20),
    },
    modalContent: {
        backgroundColor: 'white',
        borderRadius: scale(16),
        width: '100%',
        maxWidth: scale(400),
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.25,
        shadowRadius: 8,
        elevation: 8,
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: scale(20),
        paddingVertical: verticalScale(16),
        borderBottomWidth: 1,
        borderBottomColor: '#f3f4f6',
    },
    headerLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(8),
    },
    headerTitle: {
        fontSize: scale(18),
        fontWeight: 'bold',
        color: colors.primary,
    },
    closeButton: {
        padding: scale(4),
    },
    loadingContainer: {
        alignItems: 'center',
        paddingVertical: verticalScale(40),
        gap: verticalScale(12),
    },
    loadingText: {
        fontSize: scale(14),
        color: '#6b7280',
    },
    errorContainer: {
        alignItems: 'center',
        paddingVertical: verticalScale(40),
        gap: verticalScale(12),
    },
    errorText: {
        fontSize: scale(16),
        color: '#ef4444',
        textAlign: 'center',
    },
    retryButton: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(4),
        paddingHorizontal: scale(16),
        paddingVertical: verticalScale(8),
        backgroundColor: '#f0f9ff',
        borderRadius: scale(8),
        borderWidth: 1,
        borderColor: colors.primary,
    },
    retryButtonDisabled: {
        opacity: 0.6,
        backgroundColor: '#f3f4f6',
        borderColor: '#d1d5db',
    },
    retryText: {
        fontSize: scale(14),
        color: colors.primary,
        fontWeight: '600',
    },
    content: {
        paddingHorizontal: scale(20),
        paddingVertical: verticalScale(16),
        gap: verticalScale(16),
    },
    infoRow: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        gap: scale(12),
    },
    infoContent: {
        flex: 1,
    },
    infoLabel: {
        fontSize: scale(12),
        color: '#6b7280',
        fontWeight: '600',
        marginBottom: verticalScale(4),
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    infoValue: {
        fontSize: scale(15),
        color: '#1f2937',
        fontWeight: '500',
        lineHeight: scale(20),
    },
    infoValueSmall: {
        fontSize: scale(13),
        color: '#6b7280',
        fontWeight: '500',
    },
    addressLoading: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(8),
    },
    addressLoadingText: {
        fontSize: scale(14),
        color: '#6b7280',
        fontStyle: 'italic',
    },
    footer: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: scale(20),
        paddingVertical: verticalScale(16),
        borderTopWidth: 1,
        borderTopColor: '#f3f4f6',
        gap: scale(12),
    },
    refreshButton: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(6),
        paddingHorizontal: scale(16),
        paddingVertical: verticalScale(10),
        backgroundColor: '#f0f9ff',
        borderRadius: scale(8),
        borderWidth: 1,
        borderColor: colors.primary,
    },
    refreshButtonDisabled: {
        opacity: 0.6,
        backgroundColor: '#f3f4f6',
        borderColor: '#d1d5db',
    },
    refreshText: {
        fontSize: scale(14),
        color: colors.primary,
        fontWeight: '600',
    },
    mapButton: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(6),
        paddingHorizontal: scale(16),
        paddingVertical: verticalScale(10),
        backgroundColor: '#f0f9ff',
        borderRadius: scale(8),
        borderWidth: 1,
        borderColor: colors.primary,
    },
    mapText: {
        fontSize: scale(14),
        color: colors.primary,
        fontWeight: '600',
    },
});