export type NavigatorParamList = {
  ['OnBoardingScreen']: undefined;
  ['OnBoardingScreenTwo']: undefined;
  ['SignInScreen']: undefined;
  ['SignUpScreen']: undefined;
  ['ResetScreen']: undefined;
  ['VerifyScreen']: undefined;
  ['OtpScreen']: undefined;
  ['GoogleLoginWebView']: undefined;
  ['GoogleOAuthHandler']: undefined;
  ['Home']: undefined;
  ['Bookings']: undefined;
  ['Cars']: undefined;
  ['AllCars']: undefined;
  ['Profile']: undefined;
  ['CarDetail']: { id: string };
  ['BookingDetail']: { id: string };
  ['BookingForm']: { id: string } | undefined;
  ['BookingPayment']: { bookingId: string; paymentMethod: string; amount: number };
  ['PayOSWebView']: { paymentUrl: string; bookingId?: string };
  ['FeedbackForm']: { carId: string; bookingId?: string; bookingNumber?: string };
  ['CarMapScreen']: {
    pickupLocation: string;
    pickupDate: string;
    pickupTime: string;
    dropoffLocation: string;
    dropoffDate: string;
    dropoffTime: string;
    showRoute?: boolean;
  };
  ['CarMapRouteScreen']: {
    pickupLocation: string;
    pickupDate: string;
    pickupTime: string;
    dropoffLocation: string;
    dropoffDate: string;
    dropoffTime: string;
  };
  ['Staff']: undefined;
  ['StaffScreen']: undefined;
  ['PickupReturnConfirm']: {
    paymentId: string;
    bookingId?: string;
    carName?: string;
    carType?: string;
    customerName?: string;
    pickupLocation?: string;
    pickupDate?: string;
    pickupTime?: string;
    dropoffLocation?: string;
    dropoffDate?: string;
    dropoffTime?: string;
  };
  ['VehicleReturn']: { bookingId: string };
  ['PaymentHistory']: undefined;
  ['Messages']: { bookingId: string; bookingNumber?: string };
  ['ChatHeads']: undefined;
  ['Chat']: { carId: string };
  ['auth']: undefined;
  ['tabStack']: undefined;
  ['staffStack']: undefined;
  ['authStack']: undefined;
  ['rootStack']: undefined;
};

export type ScreenName = keyof NavigatorParamList;
